### PR TITLE
getSharedBreaks() to export shared breakpoints

### PR DESCRIPTION
**Pull request by marromesc**

### CODE REVIEW

**Review by argymeg — CHANGES_REQUESTED** [review]
Happy to merge this functionality (of course!), but as written I think it will only work for VCF files. Have you tested it with allele specific files?

Off the top of my head, possibly an easier way to do this would be to break up the getScoreCN function at [line 49](https://github.com/argymeg/breakclone/blob/b8c0297bc1744cf33386ce9fb32c1ab990193c25/R/copynumber.R#L49) and use the same hits_starts and hits_end objects in two different functions, one to calculate the scores and one to output the shared breaks. But if the code is too obscure at that point don't let me confuse you!

**Comment by marromesc** [comment]
Good points. That's true, it only worked for VCF files. I made it work for allele specific files too. Also, I removed redundant code making getHit function to be used by getScoreCN and exportSharedBreaks functions.

**Comment by argymeg** [comment]
Hi Maria,

I have only now noticed the same changes were made to readFunctions.R and copynumber.R, removing the file reading functions. This was done in two different commits with the same name - presumably one of the two was a mistake? Either way after a lot of head scratching on how to approach this I have reverted to the previous commit in order to try and keep a cleaner git history - hope that doesn't come off as too mean-spirited! Please do go ahead and resubmit your changes. Cheers.

**Comment by argymeg** [comment]
See also the comment from #2 about the sample1 and sample2 objects.

**Pull request merged**
