### PR TITLE
Re-roxygenized

### PR DESCRIPTION
**Pull request by adamallo**
I just re-run Roxygen2 so that the installation would not fail due to missing exported elements in NAMESPACE.

### CODE REVIEW

**Comment by argymeg** [comment]
Hi Diego,

Sorry things are a bit messy.

The first commit in this PR came as a result of #1 which I have now reverted after realising an issue thanks to your PR, so thanks for that.

For the second commit, could you explain your reasoning? The way I see it the only row-wise modification to sample1 and sample2 after they are originally generated from segmentTable is the removal of segments with a normal CN, which we indeed don't want to take into account when calculating the number of breakpoints.

Cheers.

**Comment by adamallo** [comment]
The sample1 and sample2 objects did not exist within the getScoreCN scope anymore due to the externalization of some code by a previous commit (generating the getHit function). I was just trying to fix that quickly and working with VCF data, so I did not realize that for allele-specific there were row-wise modifications happening in getHit.  Feel free to reject this pull request when you get the code working; I will be pulling from your repo. Thanks!

**Comment by argymeg** [comment]
Ah I see! You can always grab and work from the 0.3.3-doc tag unless you specifically need the getSharedBreaks functionality, in which case we'll get that working again soon.

**Comment by argymeg** [comment]
Closed as deprecating repository.

**Pull request closed without merging**
